name: New Modem Support Request
description: Request support for a cable modem model not currently supported
title: "[Modem Request] "
labels: ["enhancement", "new modem"]
body:
  - type: markdown
    attributes:
      value: |
        ## Request Support for a New Modem

        Thank you for helping expand modem support! This template will guide you through providing the information needed to add support for your modem.

        > **Please Note:** This project is maintained by a single developer in spare time. Modem requests are handled as capacity allows, with priority given to submissions that include complete, well-sanitized captures. There's no guaranteed timeline for new parser development.

        **New here?** Read [Improving the Modem Request Process](https://github.com/solentlabs/cable_modem_monitor/discussions/88) to understand what makes a complete submission.

        **The best way:** Use `har-capture` to record your modem's web interface. HAR files capture the complete HTTP flow and have a much higher success rate for parser development than HTML-only captures.

  - type: input
    id: modem-model
    attributes:
      label: Modem Model
      description: What is the exact model number of your cable modem?
      placeholder: "e.g., Netgear CM1000, Arris SB8200, Motorola MB8600"
    validations:
      required: true

  - type: input
    id: manufacturer
    attributes:
      label: Manufacturer
      description: Who makes this modem?
      placeholder: "e.g., Netgear, Arris, Motorola, Technicolor"
    validations:
      required: true

  - type: input
    id: modem-ip
    attributes:
      label: Modem IP Address
      description: What IP address does your modem use?
      placeholder: "e.g., 192.168.100.1"
    validations:
      required: true

  - type: dropdown
    id: auth-required
    attributes:
      label: Authentication Required
      description: Does your modem require a username/password to access the web interface?
      options:
        - "No - accessible without login"
        - "Yes - requires username/password"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: auth-details
    attributes:
      label: Authentication Details (if required)
      description: |
        If authentication is required, describe the login type below.

        ⚠️ **Never share your actual credentials.**
      placeholder: |
        Login type: Form-based login page / HTTP Basic Auth popup / Other
        Default username: admin (from modem label)
        Notes: Login page at /login.html
    validations:
      required: false

  - type: dropdown
    id: diagnostics-method
    attributes:
      label: How are you providing data?
      description: Choose the method you're using to share modem data
      options:
        - "HAR Capture (Recommended) - Best success rate for parser development"
        - "Fallback Mode + Capture HTML - Used built-in capture button"
        - "Haven't captured yet - Need instructions"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## 📥 How to Provide Modem Data

        ### ✅ Method 1: HAR Capture (RECOMMENDED)

        **HAR files have a much higher success rate** for parser development than HTML-only captures. They record the complete HTTP flow including authentication, headers, and async API calls.

        ```bash
        # Install har-capture (one-time)
        pip install har-capture

        # Capture from your modem
        har-capture capture 192.168.100.1
        ```

        **During capture:**
        1. Log in if your modem requires authentication
        2. Visit **all pages** - status, settings, system info, restart/reboot
        3. Wait 3-5 seconds on each page for async data to load
        4. If your modem requires auth, **log out** before closing the browser
        5. Close the browser when done

        **Before sharing:** Search the `.sanitized.har` file for your WiFi password and any other credentials - the sanitizer is best-effort but HAR files are complex. Attach the `.sanitized.har.gz` file to this issue.

        See [har-capture documentation](https://github.com/solentlabs/har-capture) for more options.

        ---

        ### 📋 Method 2: Fallback Mode + Capture HTML

        **Use this if** you can't run the HAR capture tool. Note: HTML-only captures often require follow-up requests for additional data.

        1. **Install the integration** via HACS or manually
        2. **Add your modem** (Settings → Devices & Services → Add Integration → Cable Modem Monitor)
        3. Enter your modem's IP address (e.g., `192.168.100.1`)
        4. If your modem isn't recognized, the integration enters **Fallback Mode** automatically
        5. **Click the "Capture HTML" button** on your modem device
        6. **Download Diagnostics** (three dots menu → Download Diagnostics)
        7. **Attach the JSON file** to this issue

        > ⚠️ **Before sharing:** Automated sanitization is best-effort. Please search your diagnostics file for your WiFi password and SSID to verify they're not present.

  - type: textarea
    id: files-attached
    attributes:
      label: Files Attached
      description: List the files you're attaching (drag and drop files below this form)
      placeholder: |
        Preferred:
        - modem_capture.sanitized.har.gz (from har-capture)

        Alternative:
        - diagnostics_cable_modem_monitor_xyz.json (from Fallback Mode)
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might help? (ISP, firmware version, URL patterns you discovered, etc.)
      placeholder: |
        - ISP: Comcast/Xfinity
        - Firmware version: 1.0.0.15
        - Status page URL: http://192.168.100.1/cmconnectionstatus.html
        - Notes: Modem uses HNAP protocol
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have provided a HAR capture, OR used Fallback Mode + Capture HTML
          required: true
        - label: I have searched my capture file for my WiFi SSID and password to verify they're not present
          required: true
        - label: I understand this is a solo-maintained project with no guaranteed timeline for new parsers
          required: true
        - label: I'm willing to test the parser once it's developed
          required: false

  - type: markdown
    attributes:
      value: |
        ---

        ## 🙏 Thank You!

        Your contribution helps everyone with the same modem model. Once the parser is developed, we'll ask you to test it and provide feedback.

        **Tip:** If you want to help test development branches, see the [Testing on HA guide](https://github.com/solentlabs/cable_modem_monitor/blob/main/docs/setup/TESTING_ON_HA.md).
