name: New Modem Support Request
description: Request support for a cable modem model not currently supported
title: "[Modem Request] "
labels: ["enhancement", "new modem"]
body:
  - type: markdown
    attributes:
      value: |
        ## Request Support for a New Modem

        Thank you for helping expand modem support! This template will guide you through providing the information needed to add support for your modem.

        **The easiest way:** Install the integration with your modem's IP address. Even if your modem isn't supported, it will enter **Fallback Mode** which lets you capture data safely.

  - type: input
    id: modem-model
    attributes:
      label: Modem Model
      description: What is the exact model number of your cable modem?
      placeholder: "e.g., Netgear CM1000, Arris SB8200, Motorola MB8600"
    validations:
      required: true

  - type: input
    id: manufacturer
    attributes:
      label: Manufacturer
      description: Who makes this modem?
      placeholder: "e.g., Netgear, Arris, Motorola, Technicolor"
    validations:
      required: true

  - type: input
    id: modem-ip
    attributes:
      label: Modem IP Address
      description: What IP address does your modem use?
      placeholder: "e.g., 192.168.100.1"
    validations:
      required: true

  - type: dropdown
    id: auth-required
    attributes:
      label: Authentication Required
      description: Does your modem require a username/password to access the web interface?
      options:
        - "No - accessible without login"
        - "Yes - requires username/password"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: auth-details
    attributes:
      label: Authentication Details (if required)
      description: |
        If authentication is required, what type of login does your modem use?
        DO NOT share your actual password - just describe the login type.
      placeholder: |
        Login type: Form-based login page / HTTP Basic Auth popup / Other
        Default username: admin (check modem label)
        Notes: Login page at /login.html
    validations:
      required: false

  - type: dropdown
    id: diagnostics-method
    attributes:
      label: How are you providing data?
      description: Choose the method you're using to share modem data
      options:
        - "Fallback Mode + Capture HTML (Recommended) - Used built-in capture button"
        - "HAR Capture - Used playwright script (for auth issues)"
        - "Built-in Diagnostics - Downloaded diagnostics JSON from HA"
        - "Haven't captured yet - Need instructions"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## 📥 How to Provide Modem Data

        ### ✅ Method 1: Fallback Mode + Capture HTML (RECOMMENDED)

        **This is the easiest and safest method** - works even if your modem isn't supported yet!

        1. **Install the integration** via HACS or manually
        2. **Add your modem** (Settings → Devices & Services → Add Integration → Cable Modem Monitor)
        3. Enter your modem's IP address (e.g., `192.168.100.1`)
        4. If your modem isn't recognized, the integration enters **Fallback Mode** automatically
        5. **Click the "Capture HTML" button** on your modem device
        6. **Download Diagnostics** (three dots menu → Download Diagnostics)
        7. **Attach the JSON file** to this issue

        **Why this method is best:**
        - ✅ Automatic PII sanitization (MAC addresses, serial numbers, IPs removed)
        - ✅ Captures all relevant pages automatically
        - ✅ No developer tools needed

        > ⚠️ **Before sharing:** Automated sanitization is best-effort. Please search your diagnostics file for your WiFi password and SSID to verify they're not present. See the [Modem Request Guide](https://github.com/solentlabs/cable_modem_monitor/blob/main/docs/MODEM_REQUEST.md) for details.

        ---

        ### 🔐 Method 2: HAR Capture (For Authentication Issues)

        **Use this only if** your modem requires login AND Fallback Mode can't reach the status pages.

        HAR capture records the full authentication flow, which helps us understand login requirements.

        ```bash
        # Clone the repo first
        git clone https://github.com/solentlabs/cable_modem_monitor.git
        cd cable_modem_monitor

        # Install playwright and run capture
        pip install playwright
        playwright install chromium
        python scripts/capture_modem.py
        ```

        The script **automatically sanitizes** passwords and sensitive data before saving.

        See [HAR Capture Guide](https://github.com/solentlabs/cable_modem_monitor/blob/main/docs/HAR_CAPTURE_GUIDE.md) for detailed instructions.

        ---

        ### ⚠️ Method 3: Manual HTML Capture (Last Resort)

        **Only use this if Methods 1 and 2 don't work for your situation.**

        > **🛑 PII WARNING:** Manually captured HTML often contains sensitive information!
        >
        > Before sharing, you MUST manually review and remove:
        > - MAC addresses (format: `AA:BB:CC:DD:EE:FF`)
        > - Serial numbers
        > - Account IDs
        > - IP addresses (except common modem IPs like 192.168.100.1)
        > - Any passwords or session tokens
        >
        > **We strongly recommend Method 1 instead**, which handles sanitization automatically.

        If you must capture manually:
        1. Open your modem's web interface in a browser
        2. Navigate to signal/status pages
        3. Right-click → View Page Source (Ctrl+U)
        4. **Review for PII before saving**
        5. Save and attach HTML files

  - type: textarea
    id: files-attached
    attributes:
      label: Files Attached
      description: List the files you're attaching (drag and drop files below this form)
      placeholder: |
        Preferred:
        - diagnostics_cable_modem_monitor_xyz.json (from Fallback Mode)

        Or:
        - modem_capture.har (from HAR capture script)

        Last resort (ensure PII is removed!):
        - status_page.html
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might help? (ISP, firmware version, URL patterns you discovered, etc.)
      placeholder: |
        - ISP: Comcast/Xfinity
        - Firmware version: 1.0.0.15
        - Status page URL: http://192.168.100.1/cmconnectionstatus.html
        - Notes: Modem uses HNAP protocol
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have used Fallback Mode + Capture HTML, OR sanitized my files to remove PII
          required: true
        - label: I have searched my capture file for my WiFi SSID and password to verify they're not present
          required: true
        - label: I understand this may take time as it requires developing a custom parser
          required: true
        - label: I'm willing to test the parser once it's developed
          required: false

  - type: markdown
    attributes:
      value: |
        ---

        ## 🙏 Thank You!

        Your contribution helps everyone with the same modem model. Once the parser is developed, we'll ask you to test it and provide feedback.

        **Tip:** If you want to help test development branches, see the [Testing on HA guide](https://github.com/solentlabs/cable_modem_monitor/blob/main/docs/setup/TESTING_ON_HA.md).
