#!/bin/bash
# Post-start message for dev container
# This runs every time the container starts

echo ""
echo "=========================================="
echo "🚀 Dev Container Ready!"
echo "=========================================="
echo ""
echo "Next steps to test the integration:"
echo ""
echo "1️⃣  Start Home Assistant:"
echo "   Ctrl+Shift+P → Tasks: Run Task → 'HA: Start (Fresh)'"
echo "   Wait ~1 minute for startup, then open: http://localhost:8123"
echo ""
echo "2️⃣  Create account and add integration:"
echo "   • Complete Home Assistant onboarding"
echo "   • Go to Settings → Devices & Services → Add Integration"
echo "   • Search for 'Cable Modem Monitor'"
echo ""
echo "3️⃣  Run tests:"
echo "   Ctrl+Shift+P → Tasks: Run Task → 'Run All Tests'"
echo ""
echo "📋 View all available tasks: Ctrl+Shift+P → Tasks: Run Task"
echo ""
