#!/bin/bash
# Local test runner for Cable Modem Monitor integration
# This script sets up a virtual environment and runs all tests locally
# before pushing to GitHub, preventing CI failures.

set -e  # Exit on error

echo "=========================================="
echo "Cable Modem Monitor - Local Test Runner"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Self-heal a missing or incomplete venv (e.g. after a wipe) instead of failing
# later with dozens of collection errors that look like broken code. Skipped
# entirely when the environment is already healthy, so the common path is fast.
if [ ! -d ".venv" ] || ! .venv/bin/python -c "import solentlabs.cable_modem_monitor_core" 2>/dev/null; then
    bash scripts/dev/setup_env.sh
    echo ""
fi

# Activate virtual environment
echo -e "${YELLOW}Activating virtual environment...${NC}"
source .venv/bin/activate
echo -e "${GREEN}✓ Virtual environment activated${NC}"
echo ""

# Every check below records failure here; nothing sets it back to true, so
# one red step cannot be masked by a later green one.
TEST_PASSED=true

# Run linting — these three commands are exactly what CI's lint job runs
# (.github/workflows/tests.yml § Lint with ruff / black / mypy). Any
# narrower local form can pass a tree CI rejects. Concretely: the
# pre-commit mypy hook is scoped to ^packages/[^/]+/solentlabs/, so a type
# error in custom_components/ clears every local hook and fails CI, and
# black was not run locally at all. Keep these three identical to CI.
echo -e "${YELLOW}Running code quality checks (ruff, black, mypy)...${NC}"
if ruff check .; then
    echo -e "${GREEN}✓ ruff passed${NC}"
else
    echo -e "${RED}✗ ruff failed${NC}"
    TEST_PASSED=false
fi
if black --check .; then
    echo -e "${GREEN}✓ black passed${NC}"
else
    echo -e "${RED}✗ black failed — run: black .${NC}"
    TEST_PASSED=false
fi
if mypy . --config-file=mypy.ini; then
    echo -e "${GREEN}✓ mypy passed${NC}"
else
    echo -e "${RED}✗ mypy failed${NC}"
    TEST_PASSED=false
fi
echo ""

# Run HA integration tests (coverage gate mirrors CI tests.yml: --cov-fail-under=95)
echo -e "${YELLOW}Running HA integration tests...${NC}"
if pytest tests/ -v --tb=short --cov=custom_components/cable_modem_monitor --cov-report=term --cov-report=html --cov-fail-under=95; then
    echo -e "${GREEN}✓ HA integration tests passed!${NC}"
else
    echo -e "${RED}✗ HA integration tests failed${NC}"
    TEST_PASSED=false
fi
echo ""

# Run Core package tests (coverage gate mirrors CI tests.yml: --cov-fail-under=95)
echo -e "${YELLOW}Running Core package tests...${NC}"
if (cd packages/cable_modem_monitor_core && pytest tests/ -v --tb=short --cov=solentlabs/cable_modem_monitor_core --cov-report=term-missing --cov-fail-under=95); then
    echo -e "${GREEN}✓ Core package tests passed!${NC}"
else
    echo -e "${RED}✗ Core package tests failed${NC}"
    TEST_PASSED=false
fi
echo ""

# Run Catalog package tests (coverage gate mirrors CI tests.yml: --cov-fail-under=95)
echo -e "${YELLOW}Running Catalog package tests...${NC}"
if (cd packages/cable_modem_monitor_catalog && pytest tests/ -v --tb=short --cov=solentlabs/cable_modem_monitor_catalog --cov-report=term-missing --cov-fail-under=95); then
    echo -e "${GREEN}✓ Catalog package tests passed!${NC}"
else
    echo -e "${RED}✗ Catalog package tests failed${NC}"
    TEST_PASSED=false
fi
echo ""

# Run Catalog Tools package tests (coverage gate mirrors CI tests.yml: --cov-fail-under=90)
echo -e "${YELLOW}Running Catalog Tools package tests...${NC}"
if (cd packages/cable_modem_monitor_catalog_tools && pytest tests/ -v --tb=short --cov=solentlabs/cable_modem_monitor_catalog_tools --cov-report=term-missing --cov-fail-under=90); then
    echo -e "${GREEN}✓ Catalog Tools package tests passed!${NC}"
else
    echo -e "${RED}✗ Catalog Tools package tests failed${NC}"
    TEST_PASSED=false
fi
echo ""

# Summary
echo "=========================================="
echo "Test Summary"
echo "=========================================="
if [ "$TEST_PASSED" = true ]; then
    echo -e "${GREEN}Status: READY TO PUSH ✓${NC}"
    echo ""
    echo "All checks passed! Safe to commit and push."
else
    echo -e "${RED}Status: NOT READY ✗${NC}"
    echo ""
    echo "Fix failing tests before pushing to GitHub."
fi
echo ""
echo "Coverage HTML report (HA component): open the index file under the local"
echo "coverage HTML output directory generated by pytest --cov-report=html."
echo ""
echo "To deactivate virtual environment:"
echo "  deactivate"
echo ""

# Propagate failure as a non-zero exit so `make validate-ci` and any CI mirror
# actually fails when any pytest invocation fails. Without this, the script's
# `if pytest...; then ...; else TEST_PASSED=false; fi` blocks swallow the
# pytest exit code and the script exits 0 even with failing tests — making
# the "Safe to commit and push." banner misleading and making a failing
# `make validate-ci` look green. Found in #164 post-mortem: 12 catalog
# HAR-replay tests were failing locally while the runner reported success.
if [ "$TEST_PASSED" != true ]; then
    exit 1
fi
